# Generated by Django 3.1.1 on 2020-09-04 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0004_auto_20200904_2227'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Todo_Category',
        ),
        migrations.RenameModel(
            old_name='Series',
            new_name='Todo_Series',
        ),
    ]
